name: Merge

on:
  # 手動トリガー
  workflow_dispatch:

  # PR がクローズされたときにトリガー
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  if_merged:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Calculate New Version Code
        id: calc_version
        run: echo "NEW_VERSION_CODE=$((${{vars.VERSION_CODE}} + 1))" >> $GITHUB_OUTPUT

      - name: Update Variables
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.RENOVATE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tonionagauzzi/UnusedAppFinder/actions/variables/VERSION_CODE \
          -d '{"name":"VERSION_CODE","value":"${{ steps.calc_version.outputs.NEW_VERSION_CODE }}"}'

      - name: Merged Pull Request Number and URL
        run: |
          echo "${{ github.event.pull_request.title }}"
